import Header from "@/components/Header";
import Footer from "@/components/Footer";

export default function TermsOfService() {
  return (
    <div className="flex min-h-screen flex-col bg-white">
      <Header />

      <main className="flex-1 px-4 py-10 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-3xl">
          <h1 className="text-3xl font-bold text-gray-900">Terms of Service</h1>
          <p className="mt-2 text-sm text-gray-500">Last updated: September 3, 2026</p>

          <div className="mt-8 space-y-8 text-gray-700 leading-relaxed">
            <section>
              <h2 className="text-xl font-semibold text-gray-900">1. Acceptance of Terms</h2>
              <p className="mt-3">
                By accessing or using <strong>Muawin</strong>, a voice-powered welfare assistance platform built by <strong>Aridian Technologies</strong> for <strong>Al Khidmat Foundation</strong>, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900">2. Description of Service</h2>
              <p className="mt-3">
                Muawin is an AI-powered voice assistant that provides information about Al Khidmat Foundation&apos;s welfare services, including medical care, ambulance services, donations, and other social welfare programs. The service is available in English and Urdu.
              </p>
              <p className="mt-3">
                The service is provided for informational purposes only. It does not constitute medical advice, legal advice, or emergency services. For emergencies, please call <strong>1122</strong> immediately.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900">3. Eligibility</h2>
              <p className="mt-3">
                The service is available to all individuals seeking information about Al Khidmat Foundation&apos;s welfare programs. There are no age or residency restrictions for using the informational service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900">4. User Responsibilities</h2>
              <p className="mt-3">You agree to:</p>
              <ul className="mt-3 list-disc space-y-2 pl-6">
                <li>Use the service only for lawful purposes.</li>
                <li>Not attempt to disrupt, interfere with, or gain unauthorized access to the system.</li>
                <li>Not provide false or misleading information to the assistant.</li>
                <li>Not use the service as a substitute for professional medical, legal, or emergency services.</li>
                <li>Verify critical information through official Al Khidmat Foundation channels.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900">5. Intellectual Property</h2>
              <p className="mt-3">
                All content, code, design, and technology underlying Muawin are the property of <strong>Aridian Technologies</strong>. The Al Khidmat Foundation brand, logo, and service information are the property of <strong>Al Khidmat Foundation</strong>. You may not reproduce, distribute, or create derivative works without explicit written permission.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900">6. Limitation of Liability</h2>
              <p className="mt-3">
                The service is provided &quot;as is&quot; without warranties of any kind. Aridian Technologies and Al Khidmat Foundation shall not be liable for:
              </p>
              <ul className="mt-3 list-disc space-y-2 pl-6">
                <li>Any errors or inaccuracies in the information provided by the assistant.</li>
                <li>Any decisions made based on information from the service.</li>
                <li>Any interruption or unavailability of the service.</li>
                <li>Any loss of data arising from the use of the service.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900">7. AI-Generated Content</h2>
              <p className="mt-3">
                Responses generated by the AI assistant are for informational purposes only and may not always be accurate. Always verify important information with Al Khidmat Foundation staff directly by calling the helpline at <strong>051-4853951</strong>.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900">8. Modifications to Service</h2>
              <p className="mt-3">
                We reserve the right to modify, suspend, or discontinue the service at any time without prior notice. We shall not be liable to you or any third party for any modification, suspension, or discontinuance of the service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900">9. Changes to Terms</h2>
              <p className="mt-3">
                We may revise these Terms of Service from time to time. Changes will be posted on this page with an updated &quot;Last updated&quot; date. Your continued use of the service after any changes constitutes your acceptance of the revised terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900">10. Contact Us</h2>
              <p className="mt-3">
                For questions about these Terms of Service, contact us at{" "}
                <a href="mailto:info@aridiantechnologies.com" className="text-[#0F5CC3] underline">info@aridiantechnologies.com</a>.
              </p>
            </section>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
